In [2]:
# Import Module

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [9]:
# Series
list_fruits = ['apple', 'banana', 'cherry', 'durian']

# Print the value of the 2nd index
print(list_fruits[2], '\n')

# Convert list to series
series_fruits = pd.Series(list_fruits)
print(series_fruits)

cherry

0     apple
1    banana
2    cherry
3    durian
dtype: object

In [14]:
# Series Indexing 1

# Changing the String index
series_capital = pd.Series(['Jakarta', 'Tokyo', 'London', 'France'], 
                           index=['Indonesia', 'Japan', 'UK', 'France'])

# Print the value of the series with the index UK
series_capital["UK"]
# Print the value of the series with the index 2
series_capital[2]

London
London

In [23]:
# Series Indexing 2

# Changing the number index
series_animal = pd.Series(['Elang', 'Flamingo', 'Gajah', 'Ikan'],
                          index=[100, 100, 102, 103])

series_animal[102]
# series_animal[2]
series_animal[100]

100       Elang
100    Flamingo
dtype: object

In [54]:
# Series Manipulation

# Reseting Index
# Use drop to reset to a series
# inplace to store the reset
series_animal.reset_index(drop=True, inplace=True)
series_animal 

series_gabungan = pd.concat([series_fruits, series_animal])

# Sort by Index
series_gabungan.sort_index(inplace=True)
series_gabungan.reset_index(inplace=True, drop=True)
series_gabungan

# Sort by Values
# series_gabungan.sort_values(inplace=True)
# series_gabungan.reset_index(inplace=True, drop=True)
# series_gabungan

series_gabungan[5] = 'Gorila'
series_gabungan[9] = 'Anjing'
series_gabungan['x'] = 'Brandon'

# Drop to remove value from a Series
series_gabungan.drop(labels=3, inplace=True)
series_gabungan

0      apple
1      Elang
2     banana
4     cherry
5     Gorila
6     durian
7       Ikan
9     Anjing
x    Brandon
dtype: object

In [96]:
# Data Frame

dict_1 = {'Name' : 'Andi', 'Umur' : 20, 'GPA' : 3.2, 'Grade' : 'A-', 'Gender' : 'Male', 'WNI' : True}
dict_2 = {'Name' : 'Brandon', 'Umur' : 18, 'GPA' : 3.0, 'Grade' : 'A-', 'Gender' : 'Male', 'WNI' : True}
dict_3 = {'Name' : 'Alis', 'Umur' : 22, 'GPA' : 3.8, 'Grade' : 'A', 'Gender' : 'Female', 'WNI' : True}
dict_4 = {'Name' : 'Sola', 'Umur' : 24, 'GPA' : 1.5, 'Grade' : 'C', 'Gender' : 'Male', 'WNI' : False}
dict_5 = {'Name' : 'Ed', 'Umur' : 20, 'GPA' : 3.5, 'Grade' : 'A', 'Gender' : 'Male', 'WNI' : True}
dict_6 = {'Name' : 'Lauren', 'Umur' : 21, 'GPA' : 3.6, 'Grade' : 'A', 'Gender' : 'Female', 'WNI' : True}
dict_7 = {'Name' : 'Kenneth', 'Umur' : 35, 'GPA' : 3.2, 'Grade' : 'A-', 'Gender' : 'Male', 'WNI' : False}
dict_8 = {'Name' : 'Radit', 'Umur' : 27, 'GPA' : 3.2, 'Grade' : 'A-', 'Gender' : 'Male', 'WNI' : True}
dict_9 = {'Name' : 'Felicia', 'Umur' : 17, 'GPA' : 4.0, 'Grade' : 'A', 'Gender' : 'Female', 'WNI' : False}

df_kelas = pd.DataFrame([dict_1, 
                         dict_2, 
                         dict_3, 
                         dict_4, 
                         dict_5,
                         dict_6, 
                         dict_7, 
                         dict_8, 
                         dict_9])

df_kelas

      Name  Umur  GPA Grade  Gender    WNI
0     Andi    20  3.2    A-    Male   True
1  Brandon    18  3.0    A-    Male   True
2     Alis    22  3.8     A  Female   True
3     Sola    24  1.5     C    Male  False
4       Ed    20  3.5     A    Male   True
5   Lauren    21  3.6     A  Female   True
6  Kenneth    35  3.2    A-    Male  False
7    Radit    27  3.2    A-    Male   True
8  Felicia    17  4.0     A  Female  False

In [75]:
# Query DataFrame

# Slicing
df_kelas[["Name",'GPA']]
df_kelas.loc[2:5]

# Condition
df_kelas['Grade'] = df_kelas['Grade'].str.upper()
df_kelas[df_kelas['Grade'] == 'A'][df_kelas['Gender'] == 'Female'][df_kelas['WNI'] == True]

C:\Users\kanek\AppData\Local\Temp\ipykernel_26076\2762513471.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_kelas[df_kelas['Grade'] == 'A'][df_kelas['Gender'] == 'Female'][df_kelas['WNI'] == True]

     Name  Umur  GPA Grade  Gender   WNI
2    Alis    22  3.8     A  Female  True
5  Lauren    21  3.6     A  Female  True

In [77]:
# Condition 2
df_kelas[(df_kelas['Grade'] == 'A') & (df_kelas['Gender'] == 'Female') & (df_kelas['WNI'] == True)]

      Name  Umur  GPA Grade  Gender    WNI
0     Andi    20  3.2    A-    Male   True
1  Brandon    18  3.0    A-    Male   True
2     Alis    22  3.8     A  Female   True
3     Sola    24  1.5     C    Male  False
4       Ed    20  3.5     A    Male   True
5   Lauren    21  3.6     A  Female   True
6  Kenneth    35  3.2    A-    Male  False
7    Radit    27  3.2    A-    Male   True
8  Felicia    17  4.0     A  Female  False

In [78]:
# Condition 3

df_kelas[(df_kelas['Grade'] == 'A') | (df_kelas['Gender'] == 'Male')]

      Name  Umur  GPA Grade  Gender    WNI
0     Andi    20  3.2    A-    Male   True
1  Brandon    18  3.0    A-    Male   True
2     Alis    22  3.8     A  Female   True
3     Sola    24  1.5     C    Male  False
4       Ed    20  3.5     A    Male   True
5   Lauren    21  3.6     A  Female   True
6  Kenneth    35  3.2    A-    Male  False
7    Radit    27  3.2    A-    Male   True
8  Felicia    17  4.0     A  Female  False

In [100]:
# Manipulation

dict_10 = {'Name' : 'Bung', 'Umur' : 40, 'GPA' : 1.0, 'Grade' : 'E', 'Gender' : 'Male', 'WNI' : True}

df_kelas = df_kelas.append(dict_10, ignore_index=True)
df_kelas.drop(4, axis=0, inplace=True)
df_kelas.drop('Umur', axis=1, inplace=True)
df_kelas["Strata"] = ['S1', 'S1', 'S1', 'S1', 'S1', 'S1', 'S1', 'S1', 'S1']
df_kelas

C:\Users\kanek\AppData\Local\Temp\ipykernel_26076\2464147265.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_kelas = df_kelas.append(dict_10, ignore_index=True)

      Name  GPA Grade  Gender    WNI Strata
0     Andi  3.2    A-    Male   True     S1
1  Brandon  3.0    A-    Male   True     S1
2     Alis  3.8     A  Female   True     S1
3     Sola  1.5     C    Male  False     S1
5  Felicia  4.0     A  Female  False     S1
6     Bung  1.0     E    Male   True     S1
7     Bung  1.0     E    Male   True     S1
8     Bung  1.0     E    Male   True     S1
9     Bung  1.0     E    Male   True     S1

In [101]:
df_housing = pd.read_csv()

TypeError: read_csv() missing 1 required positional argument: 'filepath_or_buffer'

In [111]:
# Describe

df_housing.info()

NameError: name 'df_housing' is not defined

In [ ]:
df_housing.describe()

In [109]:
# Describe

df_kelas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 0 to 9
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      object
 1   GPA     9 non-null      float64
 2   Grade   9 non-null      object
 3   Gender  9 non-null      object
 4   WNI     9 non-null      bool
 5   Strata  9 non-null      object
dtypes: bool(1), float64(1), object(4)
memory usage: 441.0+ bytes

In [110]:
# Describe
df_kelas.GPA.describe()

count    9.000000
mean     2.166667
std      1.307670
min      1.000000
25%      1.000000
50%      1.500000
75%      3.200000
max      4.000000
Name: GPA, dtype: float64