In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('./spotify_songs.csv')
df.head()

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.1020,0.000000,0.0653,0.518,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.0724,0.004210,0.3570,0.693,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.0794,0.000023,0.1100,0.613,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.0287,0.000009,0.2040,0.277,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.0803,0.000000,0.0833,0.725,123.976,189052

In [3]:
# Check for dataset size and basic info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32833 entries, 0 to 32832
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   track_id                  32833 non-null  object
 1   track_name                32828 non-null  object
 2   track_artist              32828 non-null  object
 3   track_popularity          32833 non-null  int64
 4   track_album_id            32833 non-null  object
 5   track_album_name          32828 non-null  object
 6   track_album_release_date  32833 non-null  object
 7   playlist_name             32833 non-null  object
 8   playlist_id               32833 non-null  object
 9   playlist_genre            32833 non-null  object
 10  playlist_subgenre         32833 non-null  object
 11  danceability              32833 non-null  float64
 12  energy                    32833 non-null  float64
 13  key                       32833 non-null  int64
 14  loudness                  32833 non-null  float64
 15  mode                      32833 non-null  int64
 16  speechiness               32833 non-null  float64
 17  acousticness              32833 non-null  float64
 18  instrumentalness          32833 non-null  float64
 19  liveness                  32833 non-null  float64
 20  valence                   32833 non-null  float64
 21  tempo                     32833 non-null  float64
 22  duration_ms               32833 non-null  int64
dtypes: float64(9), int64(4), object(10)
memory usage: 5.8+ MB

In [4]:
# Check for missing value
df.isnull().sum()

track_id                    0
track_name                  5
track_artist                5
track_popularity            0
track_album_id              0
track_album_name            5
track_album_release_date    0
playlist_name               0
playlist_id                 0
playlist_genre              0
playlist_subgenre           0
danceability                0
energy                      0
key                         0
loudness                    0
mode                        0
speechiness                 0
acousticness                0
instrumentalness            0
liveness                    0
valence                     0
tempo                       0
duration_ms                 0
dtype: int64

In [5]:
# Drop Null Value
df.dropna(inplace=True)
df.isnull().sum()

track_id                    0
track_name                  0
track_artist                0
track_popularity            0
track_album_id              0
track_album_name            0
track_album_release_date    0
playlist_name               0
playlist_id                 0
playlist_genre              0
playlist_subgenre           0
danceability                0
energy                      0
key                         0
loudness                    0
mode                        0
speechiness                 0
acousticness                0
instrumentalness            0
liveness                    0
valence                     0
tempo                       0
duration_ms                 0
dtype: int64

In [6]:
# Remove Useless Variables
df.drop(['track_id', 'track_name', 
         'track_album_id', 'track_album_name', 
         'track_album_release_date', 'track_artist', 
         'playlist_name', 'playlist_id'], axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32828 entries, 0 to 32832
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   track_popularity   32828 non-null  int64
 1   playlist_genre     32828 non-null  object
 2   playlist_subgenre  32828 non-null  object
 3   danceability       32828 non-null  float64
 4   energy             32828 non-null  float64
 5   key                32828 non-null  int64
 6   loudness           32828 non-null  float64
 7   mode               32828 non-null  int64
 8   speechiness        32828 non-null  float64
 9   acousticness       32828 non-null  float64
 10  instrumentalness   32828 non-null  float64
 11  liveness           32828 non-null  float64
 12  valence            32828 non-null  float64
 13  tempo              32828 non-null  float64
 14  duration_ms        32828 non-null  int64
dtypes: float64(9), int64(4), object(2)
memory usage: 4.0+ MB

In [7]:
# Check for outliers
def find_outliers(col):
    q1 = col.quantile(.25)
    q3 = col.quantile(.75)
    IQR = q3 - q1
    ll = q1 - (1.5*IQR)
    ul = q3 + (1.5*IQR)
    upper_outliers = col[col > ul].index.tolist()
    lower_outliers = col[col < ll].index.tolist()
    bad_indices = list(set(upper_outliers + lower_outliers))
    return(bad_indices)

import numpy as np
bad_indexes = []
for col in df.columns:
    if df[col].dtype in ["int64","float64"]:
        bad_indexes.append(find_outliers(df[col]))

bad_indexes = set(list(np.concatenate(bad_indexes).flat))
print(len(bad_indexes))

13605

Ignore Outliers for now

In [8]:
# Preprocessing
# One Hot Encoding
ohe_data = pd.get_dummies(df, columns=['playlist_genre'], dtype=int)
ohe_data.head()

,track_popularity,playlist_subgenre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,playlist_genre_edm,playlist_genre_latin,playlist_genre_pop,playlist_genre_r&b,playlist_genre_rap,playlist_genre_rock
0,66,dance pop,0.748,0.916,6,-2.634,1,0.0583,0.1020,0.000000,0.0653,0.518,122.036,194754,0,0,1,0,0,0
1,67,dance pop,0.726,0.815,11,-4.969,1,0.0373,0.0724,0.004210,0.3570,0.693,99.972,162600,0,0,1,0,0,0
2,70,dance pop,0.675,0.931,1,-3.432,0,0.0742,0.0794,0.000023,0.1100,0.613,124.008,176616,0,0,1,0,0,0
3,60,dance pop,0.718,0.930,7,-3.778,1,0.1020,0.0287,0.000009,0.2040,0.277,121.956,169093,0,0,1,0,0,0
4,69,dance pop,0.650,0.833,1,-4.672,1,0.0359,0.0803,0.000000,0.0833,0.725,123.976,189052,0,0,1,0,0,0

In [9]:
ohe_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32828 entries, 0 to 32832
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_popularity      32828 non-null  int64
 1   playlist_subgenre     32828 non-null  object
 2   danceability          32828 non-null  float64
 3   energy                32828 non-null  float64
 4   key                   32828 non-null  int64
 5   loudness              32828 non-null  float64
 6   mode                  32828 non-null  int64
 7   speechiness           32828 non-null  float64
 8   acousticness          32828 non-null  float64
 9   instrumentalness      32828 non-null  float64
 10  liveness              32828 non-null  float64
 11  valence               32828 non-null  float64
 12  tempo                 32828 non-null  float64
 13  duration_ms           32828 non-null  int64
 14  playlist_genre_edm    32828 non-null  int32
 15  playlist_genre_latin  32828 non-null  int32
 16  playlist_genre_pop    32828 non-null  int32
 17  playlist_genre_r&b    32828 non-null  int32
 18  playlist_genre_rap    32828 non-null  int32
 19  playlist_genre_rock   32828 non-null  int32
dtypes: float64(9), int32(6), int64(4), object(1)
memory usage: 4.5+ MB

## Classification

In [10]:
from sklearn.metrics import classification_report

#### Split Data

In [11]:
input_df = ohe_data.drop('playlist_subgenre', axis=1)
output_df = ohe_data['playlist_subgenre']

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(input_df, output_df, test_size=0.25, random_state=1)

#### Decission Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier

dt_class = DecisionTreeClassifier()
dt_class.fit(x_train, y_train)

DecisionTreeClassifier()

In [14]:
predict_dt = dt_class.predict(x_test)

In [15]:
print('Classification Report')
print(classification_report(y_test, predict_dt))

Classification Report
                           precision    recall  f1-score   support

               album rock       0.25      0.29      0.27       279
                 big room       0.28      0.29      0.29       277
             classic rock       0.25      0.23      0.24       349
                dance pop       0.33      0.39      0.36       326
            electro house       0.35      0.39      0.37       346
               electropop       0.33      0.33      0.33       369
             gangster rap       0.33      0.40      0.36       344
                hard rock       0.45      0.46      0.45       380
                  hip hop       0.46      0.42      0.44       351
                  hip pop       0.37      0.38      0.38       314
          indie poptimism       0.43      0.40      0.42       435
            latin hip hop       0.38      0.43      0.41       396
                latin pop       0.30      0.28      0.29       318
                 neo soul       0.41      0.44      0.43       382
           new jack swing       0.54      0.56      0.55       279
           permanent wave       0.33      0.31      0.32       284
                  pop edm       0.51      0.44      0.47       404
            post-teen pop       0.31      0.28      0.29       297
progressive electro house       0.39      0.39      0.39       440
                reggaeton       0.29      0.25      0.27       241
         southern hip hop       0.46      0.44      0.45       429
                     trap       0.43      0.42      0.43       322
                 tropical       0.54      0.54      0.54       299
       urban contemporary       0.30      0.27      0.28       346

                 accuracy                           0.38      8207
                macro avg       0.38      0.38      0.38      8207
             weighted avg       0.38      0.38      0.38      8207

#### KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier

knn_class = KNeighborsClassifier()
knn_class.fit(x_train, y_train)

KNeighborsClassifier()

In [24]:
predict_knn = knn_class.predict(x_test)

In [25]:
print('Classification Report')
print(classification_report(y_test, predict_knn))

Classification Report
                           precision    recall  f1-score   support

               album rock       0.04      0.13      0.07       279
                 big room       0.06      0.20      0.09       277
             classic rock       0.06      0.11      0.08       349
                dance pop       0.05      0.11      0.07       326
            electro house       0.06      0.14      0.08       346
               electropop       0.05      0.07      0.06       369
             gangster rap       0.08      0.10      0.09       344
                hard rock       0.08      0.07      0.08       380
                  hip hop       0.17      0.14      0.15       351
                  hip pop       0.05      0.03      0.04       314
          indie poptimism       0.07      0.04      0.05       435
            latin hip hop       0.07      0.04      0.05       396
                latin pop       0.03      0.01      0.02       318
                 neo soul       0.06      0.04      0.05       382
           new jack swing       0.14      0.11      0.12       279
           permanent wave       0.13      0.04      0.06       284
                  pop edm       0.09      0.03      0.05       404
            post-teen pop       0.08      0.03      0.04       297
progressive electro house       0.18      0.12      0.15       440
                reggaeton       0.08      0.03      0.04       241
         southern hip hop       0.12      0.05      0.07       429
                     trap       0.10      0.04      0.06       322
                 tropical       0.08      0.05      0.06       299
       urban contemporary       0.02      0.01      0.01       346

                 accuracy                           0.07      8207
                macro avg       0.08      0.07      0.07      8207
             weighted avg       0.08      0.07      0.07      8207

#### Logistic Regresion

In [27]:
from sklearn.linear_model import LogisticRegression

lr_class = LogisticRegression()
lr_class.fit(x_train, y_train)

LogisticRegression()

In [28]:
predict_lr = lr_class.predict(x_test)

In [30]:
print('Classification Report')
print(classification_report(y_test, predict_lr))

Classification Report
                           precision    recall  f1-score   support

               album rock       0.00      0.00      0.00       279
                 big room       0.05      0.03      0.03       277
             classic rock       0.00      0.00      0.00       349
                dance pop       0.00      0.00      0.00       326
            electro house       0.08      0.17      0.11       346
               electropop       0.00      0.00      0.00       369
             gangster rap       0.00      0.00      0.00       344
                hard rock       0.00      0.00      0.00       380
                  hip hop       0.14      0.25      0.18       351
                  hip pop       0.20      0.01      0.01       314
          indie poptimism       0.07      0.05      0.06       435
            latin hip hop       0.05      0.13      0.07       396
                latin pop       0.00      0.00      0.00       318
                 neo soul       0.09      0.12      0.10       382
           new jack swing       0.09      0.07      0.08       279
           permanent wave       0.00      0.00      0.00       284
                  pop edm       0.08      0.13      0.10       404
            post-teen pop       0.00      0.00      0.00       297
progressive electro house       0.10      0.44      0.16       440
                reggaeton       0.00      0.00      0.00       241
         southern hip hop       0.07      0.07      0.07       429
                     trap       0.09      0.23      0.13       322
                 tropical       0.00      0.00      0.00       299
       urban contemporary       0.05      0.10      0.07       346

                 accuracy                           0.08      8207
                macro avg       0.05      0.07      0.05      8207
             weighted avg       0.05      0.08      0.05      8207

C:\Users\kanek\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kanek\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\kanek\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

#### Naive Bayes

In [32]:
from sklearn.naive_bayes import GaussianNB

nb_class = GaussianNB()
nb_class.fit(x_train, y_train)

GaussianNB()

In [33]:
predict_nb = nb_class.predict(x_test)

In [34]:
print('Classification Report')
print(classification_report(y_test, predict_nb))

Classification Report
                           precision    recall  f1-score   support

               album rock       0.23      0.07      0.11       279
                 big room       0.16      0.39      0.23       277
             classic rock       0.17      0.06      0.09       349
                dance pop       0.18      0.45      0.25       326
            electro house       0.19      0.25      0.22       346
               electropop       0.23      0.02      0.04       369
             gangster rap       0.32      0.19      0.24       344
                hard rock       0.22      0.17      0.19       380
                  hip hop       0.32      0.38      0.35       351
                  hip pop       0.31      0.21      0.25       314
          indie poptimism       0.25      0.29      0.27       435
            latin hip hop       0.29      0.08      0.13       396
                latin pop       0.30      0.14      0.19       318
                 neo soul       0.24      0.32      0.27       382
           new jack swing       0.24      0.31      0.27       279
           permanent wave       0.23      0.14      0.17       284
                  pop edm       0.37      0.37      0.37       404
            post-teen pop       0.19      0.25      0.22       297
progressive electro house       0.22      0.49      0.31       440
                reggaeton       0.24      0.20      0.22       241
         southern hip hop       0.38      0.26      0.31       429
                     trap       0.20      0.29      0.23       322
                 tropical       0.33      0.25      0.28       299
       urban contemporary       0.20      0.06      0.10       346

                 accuracy                           0.24      8207
                macro avg       0.25      0.24      0.22      8207
             weighted avg       0.25      0.24      0.22      8207