1. **Import all library that we need**

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sn

In [3]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score, log_loss
from sklearn.metrics import classification_report, confusion_matrix

2.**Load the data**

In [4]:
df=pd.read_csv('user_segmentation.csv',delimiter=';')
df.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size,Segmentation
0,462809,Male,No,22,No,Healthcare,1.0,Low,4.0,D
1,462643,Female,Yes,38,Yes,Engineer,NaN,Average,3.0,A
2,466315,Female,Yes,67,Yes,Engineer,1.0,Low,1.0,B
3,461735,Male,Yes,67,Yes,Lawyer,0.0,High,2.0,B
4,462669,Female,Yes,40,Yes,Entertainment,NaN,High,6.0,A

3. **Data Observation**

We need to check:

3.a Number of data

In [5]:
print(df.shape)

(8068, 10)

In [6]:
df.columns

Index(['ID', 'Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Segmentation'],
      dtype='object')

3.b Check Missing Value and type of data

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8068 entries, 0 to 8067
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8068 non-null   int64
 1   Gender           8068 non-null   object
 2   Ever_Married     7928 non-null   object
 3   Age              8068 non-null   int64
 4   Graduated        7990 non-null   object
 5   Profession       7944 non-null   object
 6   Work_Experience  7239 non-null   float64
 7   Spending_Score   8068 non-null   object
 8   Family_Size      7733 non-null   float64
 9   Segmentation     8068 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 630.4+ KB
None

In [8]:
df['Ever_Married'].value_counts()

Ever_Married
Yes    4643
No     3285
Name: count, dtype: int64

In [9]:
df['Graduated'].value_counts()

Graduated
Yes    4968
No     3022
Name: count, dtype: int64

In [10]:
df['Spending_Score'].value_counts()

Spending_Score
Low        4878
Average    1974
High       1216
Name: count, dtype: int64

4. **Split Data into Training and Testing**

In [11]:
input_df=df.drop('Segmentation',axis=1)
output_df=df['Segmentation']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(input_df, output_df, test_size = 0.2, random_state = 42)

5. **Missing Value Handling**

In [13]:
import statistics

In [14]:
statistics.mode(x_train['Ever_Married'])

'Yes'

In [15]:
statistics.mode(x_train['Graduated'])

'Yes'

In [16]:
statistics.mode(x_train['Profession'])

'Artist'

In [17]:
#Replace Missing Value for train data
x_train['Ever_Married'].fillna('Yes', inplace=True)
x_train['Graduated'].fillna('Yes', inplace=True)
x_train['Profession'].fillna('Artist', inplace=True)

In [18]:
#Replace Missing Value for test data
x_test['Ever_Married'].fillna('Yes', inplace=True)
x_test['Graduated'].fillna('Yes', inplace=True)
x_test['Profession'].fillna('Artist', inplace=True)

In [19]:
x_train.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size
2821,460591,Female,Yes,38,Yes,Doctor,1.0,Low,4.0
6192,460459,Female,No,33,No,Engineer,0.0,Low,5.0
1393,459043,Female,Yes,49,No,Engineer,1.0,Low,1.0
812,461220,Female,No,26,No,Executive,8.0,Low,3.0
2215,460403,Female,No,56,Yes,Doctor,3.0,Low,1.0

In [20]:
#Calculate Mean for Work Experience
np.mean(x_train['Work_Experience'])

2.6590163934426227

In [21]:
#Calculate Mean for Family Size
np.mean(x_train['Family_Size'])

2.8574426864707783

In [22]:
#Replace Null numeric value with their Mean for train data
x_train['Work_Experience'].fillna(2.7, inplace=True)
x_train['Family_Size'].fillna(2.9, inplace=True)

In [23]:
#Replace Null numeric value with their Mean for train data
x_test['Work_Experience'].fillna(2.7, inplace=True)
x_test['Family_Size'].fillna(2.9, inplace=True)

In [24]:
x_train.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size
2821,460591,Female,Yes,38,Yes,Doctor,1.0,Low,4.0
6192,460459,Female,No,33,No,Engineer,0.0,Low,5.0
1393,459043,Female,Yes,49,No,Engineer,1.0,Low,1.0
812,461220,Female,No,26,No,Executive,8.0,Low,3.0
2215,460403,Female,No,56,Yes,Doctor,3.0,Low,1.0

In [25]:
print(x_train.info())

<class 'pandas.core.frame.DataFrame'>
Index: 6454 entries, 2821 to 7270
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               6454 non-null   int64
 1   Gender           6454 non-null   object
 2   Ever_Married     6454 non-null   object
 3   Age              6454 non-null   int64
 4   Graduated        6454 non-null   object
 5   Profession       6454 non-null   object
 6   Work_Experience  6454 non-null   float64
 7   Spending_Score   6454 non-null   object
 8   Family_Size      6454 non-null   float64
dtypes: float64(2), int64(2), object(5)
memory usage: 504.2+ KB
None

6. **Feature Encoding**

In [38]:
#encode non numeric data into numeric data
#encode Gender Graduateand ever married
train_encode={"Gender": {"Male":1,"Female" :0}, "Ever_Married":{"Yes":1, "No":0}, "Graduated":{"Yes":1, "No":0}}
test_encode={"Gender": {"Male":1,"Female" :0}, "Ever_Married":{"Yes":1, "No":0}, "Graduated":{"Yes":1, "No":0}}

#replace categorical value into numerical value
x_train=x_train.replace(train_encode)
x_test=x_test.replace(test_encode)

In [39]:
x_train.head()

,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,Family_Size
2821,460591,0,1,38,1,Doctor,1.0,Low,4.0
6192,460459,0,0,33,0,Engineer,0.0,Low,5.0
1393,459043,0,1,49,0,Engineer,1.0,Low,1.0
812,461220,0,0,26,0,Executive,8.0,Low,3.0
2215,460403,0,0,56,1,Doctor,3.0,Low,1.0

In [42]:
from sklearn.preprocessing import OneHotEncoder
#encoded profession and spending score for training data
x=x_train[['Profession','Spending_Score']]
train_encoded=OneHotEncoder()
train_data=pd.DataFrame(train_encoded.fit_transform(x).toarray(),columns=train_encoded.get_feature_names_out())
x_train=x_train.reset_index()
x_train_enc=pd.concat([x_train,train_data], axis=1)

In [43]:
x_train_enc.head()

,level_0,index,ID,Gender,Ever_Married,Age,Graduated,Profession,Work_Experience,Spending_Score,...,Profession_Engineer,Profession_Entertainment,Profession_Executive,Profession_Healthcare,Profession_Homemaker,Profession_Lawyer,Profession_Marketing,Spending_Score_Average,Spending_Score_High,Spending_Score_Low
0,0,2821,460591,0,1,38,1,Doctor,1.0,Low,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,6192,460459,0,0,33,0,Engineer,0.0,Low,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,2,1393,459043,0,1,49,0,Engineer,1.0,Low,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,3,812,461220,0,0,26,0,Executive,8.0,Low,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4,2215,460403,0,0,56,1,Doctor,3.0,Low,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [44]:
#encoded profession and spending score for testing data
x=x_test[['Profession','Spending_Score']]
test_data=pd.DataFrame(train_encoded.transform(x).toarray(),columns=train_encoded.get_feature_names_out())
x_test=x_test.reset_index()
x_test_enc=pd.concat([x_test,test_data], axis=1)

In [46]:
x_train_enc.columns

Index(['level_0', 'index', 'ID', 'Gender', 'Ever_Married', 'Age', 'Graduated',
       'Profession', 'Work_Experience', 'Spending_Score', 'Family_Size',
       'Profession_Artist', 'Profession_Doctor', 'Profession_Engineer',
       'Profession_Entertainment', 'Profession_Executive',
       'Profession_Healthcare', 'Profession_Homemaker', 'Profession_Lawyer',
       'Profession_Marketing', 'Spending_Score_Average', 'Spending_Score_High',
       'Spending_Score_Low'],
      dtype='object')

In [47]:
x_train=x_train_enc[['Gender', 'Ever_Married', 'Age', 'Graduated', 
                     'Work_Experience', 'Family_Size','Profession_Artist', 
                     'Profession_Doctor', 'Profession_Engineer',
                     'Profession_Entertainment', 'Profession_Executive',
                     'Profession_Healthcare', 'Profession_Homemaker', 
                     'Profession_Lawyer','Profession_Marketing', 
                     'Spending_Score_Average', 'Spending_Score_High',
                     'Spending_Score_Low' ]]

In [49]:
x_test=x_test_enc[['Gender', 'Ever_Married', 'Age', 'Graduated', 
                     'Work_Experience', 'Family_Size','Profession_Artist', 
                     'Profession_Doctor', 'Profession_Engineer',
                     'Profession_Entertainment', 'Profession_Executive',
                     'Profession_Healthcare', 'Profession_Homemaker', 
                     'Profession_Lawyer','Profession_Marketing', 
                     'Spending_Score_Average', 'Spending_Score_High',
                     'Spending_Score_Low' ]]

7. **Prediction Model**

In [48]:
from sklearn.tree import DecisionTreeClassifier
dectree = DecisionTreeClassifier()
dectree.fit(x_train, y_train)

DecisionTreeClassifier()

In [50]:
y_predict=dectree.predict(x_test)

8. **Calculate Performance of The Model**

In [52]:
print('\nClassification Report\n')
print(classification_report(y_test, y_predict, target_names=['A', 'B', 'C','D']))

Classification Report

              precision    recall  f1-score   support

           A       0.37      0.40      0.38       391
           B       0.32      0.35      0.33       369
           C       0.45      0.44      0.44       380
           D       0.65      0.57      0.61       474

    accuracy                           0.45      1614
   macro avg       0.45      0.44      0.44      1614
weighted avg       0.46      0.45      0.45      1614

#Thank You